# Generated by Django 3.2.5 on 2022-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('customer', 'customer')], default='customer', max_length=255),
        ),
    ]
